### PR TITLE
FIX (merge?) Updates for new jenkins server

### PR DESCRIPTION
**Pull request by dylex**
Along with some other cleanups and efficiency improvements to test framework.

### CODE REVIEW

**Comment by edouardoyallon** [comment]
I think it'd be awesome if we could have back this continuous-integration software!

**Comment by dylex** [comment]
Thanks for the reminder.  I think I've gotten this working again the nvidia way -- nvidia-container-runtime and nvidia/cuda:9.2 docker image -- which is simpler anyway.  (The current python packages don't work with cuda 10.)  Should be safe to merge/rebase at this point, @janden.

**Comment by eickenberg** [comment]
This LGTM.

Wondering how is best to merge given that some of the commits fail the Jenkins tests.

Should we 
a) squash them to remove the failed commits (so that in the future the only failed commits are in WIP pull requests)

or

b) rebase and keep the commit history because it is informative/useful in some way?

**Comment by dylex** [comment]
Squashing is fine -- I've rebased now to clean up history.

**Comment by edouardoyallon** [comment]
Thanks so much!

**Pull request merged**
