### PR TITLE
ENH(WIP) adding meta to 2D scattering

### LINKED ISSUE #376: Accessing coefficients layer wise
I am trying to compare the energy of the signal at different levels of the scattering response. However, I have trouble pointing out which index value corresponds to which level?
Please refer to the code below taken from MNIST classification:

```python
import torch.nn as nn
import torch.optim
from torchvision import datasets, transforms
import torch.nn.functional as F
from kymatio import Scattering2D
import kymatio.datasets as scattering_datasets
import numpy as np 
myDataSet = datasets.MNIST(scattering_datasets.get_dataset_dir('MNIST'),train=True, download=True,transform=transforms.Compose([ transforms.ToTensor()]))
train_loader = torch.utils.data.DataLoader(myDataSet,shuffle=True,batch_size=1)
dataiter = iter(train_loader)
images, labels = dataiter.next()
scattering = Scattering2D(J=2, shape=(28, 28),max_order=2,L=8)
val = scattering.forward(images)
scatterImage = val.detach().numpy()
print(scatterImage.shape)
```
This gives the scatterinf response (1, 1, 81,7,7). However, I am not sure which index corresponds to which level.

Also, I would like to apply SVM to scattering response but am not sure how to handle the data point with dimensions (81,7,7) for each datapoint. Can someone point me in the right direction ?

### PR DESCRIPTION
**Pull request by edouardoyallon**
Close #376 

Adding a routine similar to 1D's meta to 2D.

### CODE REVIEW

**Comment by eickenberg** [comment]
The way this should be done is by outputting a dictionary with tuple indices that point to the right places

**Comment by eickenberg** [comment]
Why does the array output need to be torch arrays?

As far as I can tell, these dictionaries don't point to the actual data. So this seems quite awkward to me (I am aware we have something like this in another part of the code base)

**Comment by edouardoyallon** [comment]
> The way this should be done is by outputting a dictionary with tuple indices that point to the right places

Do you have an idea of output you would like to get? I'm not sure to understand, as here meta[index] would have info about the coordinate meta.

**Comment by janden** [comment]
IIRC the reason this is done in 1D is to simplify logical indexing of the output. In other words, you can do something like `S[order==1, ...]` and have it work without barking at you. Now whether it's a good idea or not is a different question. We should maybe default all of these fields to numpy arrays or (gasp) Python lists.

**Comment by edouardoyallon** [comment]
I'm up to follow any clear methodology for this! Any suggestions?

**Comment by edouardoyallon** [comment]
@eickenberg @lostanlen @janden any suggestions?

**Pull request closed without merging**
