### PR TITLE
FIX(ENH?) Torch17 support

### LINKED ISSUE #678: TypeError: 'module' object is not callable, in the progress of computing scattering by ScatteringTorch1D
Hello, all.
I tried fsdd classification in example projects (https://www.kymat.io/gallery_1d/plot_classif_torch.html#sphx-glr-gallery-1d-plot-classif-torch-py), but the error occurred at `Sx_all = scattering.forward(x_all)`.

OS: Linux Ubuntu 
Python version 3.7
PyTorch version 1.8.0

Detail 
> /usr/local/lib/python3.7/dist-packages/kymatio/frontend/torch_frontend.py in forward(self, x)
     21         input_checks(x)
     22 
---> 23         return self.scattering(x)
     24 
     25     _doc_array = 'torch.Tensor'
>
>/usr/local/lib/python3.7/dist-packages/kymatio/scattering1d/frontend/torch_frontend.py in scattering(self, x)
    119                        vectorize=self.vectorize,
    120                        size_scattering=size_scattering,
--> 121                        out_type=self.out_type)
    122 
    123         if self.out_type == 'array' and self.vectorize:
>
>/usr/local/lib/python3.7/dist-packages/kymatio/scattering1d/core/scattering1d.py in scattering1d(x, pad, unpad, backend, J, psi1, psi2, phi, pad_left, pad_right, ind_start, ind_end, oversampling, max_order, average, size_scattering, vectorize, out_type)
     76 
     77     # compute the Fourier transform
---> 78     U_0_hat = fft(U_0, 'C2C')
     79 
     80     # Get S0
>
>/usr/local/lib/python3.7/dist-packages/kymatio/backend/base_backend.py in __call__(self, x, direction, inverse)
     56 
     57     def __call__(self, x, direction='C2C', inverse=False):
---> 58         return self.fft_forward(x, direction=direction, inverse=inverse)

>/usr/local/lib/python3.7/dist-packages/kymatio/backend/base_backend.py in fft_forward(self, x, direction, inverse)
     51                 output = self.ifft(x)
     52             else:
---> 53                 output = self.fft(x)
     54 
     55         return output
>
>/usr/local/lib/python3.7/dist-packages/kymatio/scattering1d/backend/torch_backend.py in <lambda>(x)
    132 
    133 
--> 134 fft = FFT(lambda x: torch.fft(x, 1, normalized=False),
    135     lambda x: torch.ifft(x, 1, normalized=False),
    136     lambda x: torch.irfft(x, 1, normalized=False, onesided=False),
>
>TypeError: 'module' object is not callable

Thank you,
Bitter13044

### PR DESCRIPTION
**Pull request by edouardoyallon**
This PR should:

- [x] fix the issue with the default backend for torch >=1.8
- [x] propose a backend for torch <=1.7
- [x] add the related doc
- [x] update the unit test
- [ ] update gh action
- [ ] add a unit test to try torch 17

Close #678

### CODE REVIEW

**Review by eickenberg — APPROVED** [review]
This seems like an OK hotfix for me for `master`.

However, not that we have refactored all the backends in `dev`. It would have been great to base the work off that. But we can incorporate a modification of these changes into dev and have that for the next release.

**Comment by eickenberg** [comment]
Approval pending tests ofc

**Comment by edouardoyallon** [comment]
tests require circleci/ghactions to be updated on the master... snake biting its tail

**Comment by eickenberg** [comment]
Can you first add ghactions to master then? And then this on top?

**Comment by eickenberg** [comment]
Alternatively, can you test this locally with a reasonable range of setups?
I don't like the idea of committing something untested to master.

**Comment by edouardoyallon** [comment]
> Alternatively, can you test this locally with a reasonable range of setups?
> I don't like the idea of committing something untested to master.

same here but since the tests don't pass on the master etc, it means at some point there will be a PR that must be forced

**Comment by eickenberg** [comment]
How was ghactions incorporated into dev?
This needs to happen before and importantly: separately, from this PR
(this one we might need to force)

**Comment by edouardoyallon** [comment]
> How was ghactions incorporated into dev?
> This needs to happen before and importantly: separately, from this PR
> (this one we might need to force)

Right.Tests on the master were passing when it was incorporated. I'm going to downgrade the version of pytorch, making sure the tests pass for 1.7, and THEN add this for 1.8

**Comment by eickenberg** [comment]
https://github.com/kymatio/kymatio/pull/651/files

https://github.com/kymatio/kymatio/pull/661/files

These files should be added to master in a separate PR.
Is there a blocker for this?

**Comment by eickenberg** [comment]
Now I understand.
Indeed: gh-workflows for pre1.8 needs to pass these modifications. Then gh actions needs to be updates to 1.8. Then that also needs to pass.

**Comment by edouardoyallon** [comment]
Yeah! I just realized a weakness of our pipeline is to trust otherframeworks: we should carefully specify the version we're testing, and incorporate new updates slowly (though I'd trust np, tf & scipy)

**Comment by eickenberg** [comment]
Is there any progress on the testing front here?

**Comment by sujoyrc** [comment]
@edouardoyallon what is the fix ? pip install still does not work.

**Comment by janden** [comment]
This is in master, but hasn't been packaged and uploaded to PyPI yet. You can try installing from the git repo using:
```
pip3 install git+https://github.com/kymatio/kymatio
```

**Comment by sujoyrc** [comment]
Thank you. I was using nussl library https://nussl.github.io/docs/ (version 1.1.9) to do some exploratory analysis around speech signals and spectorgrams. 

even a

`import nussl`

command without using the package anywhere makes the code fail.

```
Traceback (most recent call last):
  File "testKymatio.py", line 101, in <module>
    Sx_all = scattering.forward(x_all)
  File "/home/antpc/anaconda3/lib/python3.8/site-packages/kymatio/frontend/torch_frontend.py", line 23, in forward
    return self.scattering(x)
  File "/home/antpc/anaconda3/lib/python3.8/site-packages/kymatio/scattering1d/frontend/torch_frontend.py", line 114, in scattering
    S = scattering1d(x, self.backend.pad, self.backend.unpad, self.backend, self.J, self.psi1_f, self.psi2_f, self.phi_f,\
  File "/home/antpc/anaconda3/lib/python3.8/site-packages/kymatio/scattering1d/core/scattering1d.py", line 78, in scattering1d
    U_0_hat = fft(U_0, 'C2C')
  File "/home/antpc/anaconda3/lib/python3.8/site-packages/kymatio/backend/base_backend.py", line 58, in __call__
    return self.fft_forward(x, direction=direction, inverse=inverse)
  File "/home/antpc/anaconda3/lib/python3.8/site-packages/kymatio/backend/base_backend.py", line 53, in fft_forward
    output = self.fft(x)
  File "/home/antpc/anaconda3/lib/python3.8/site-packages/kymatio/scattering1d/backend/torch_backend.py", line 139, in <lambda>
    fft = FFT(lambda x: torch.fft(x, 1, normalized=False),
TypeError: 'module' object is not callable
```
I know you don't need to fix or make this compatible but logging it here so that anyone searching for this error can identify the issue. I spend over 3 hours debugging this comparing line by line with your sample spoken digit classification code.

Hope this is ok.

And thanks for the quick clarification yesterday.

**Comment by janden** [comment]
I'm not following. Why does importing `nussl` result in `scattering.forward` being called?

At any rate, the new version compatible with the latest Torch will be uploaded to PyPI soon.

Finally, this is a closed PR. If you have a bug report, feature request, or similar, please file an issue.

**Comment by sujoyrc** [comment]
Sorry for not being clear. I had an import statement earlier in my code as I was doing some exploratory analysis. That import statement makes the `scattering.forward` command  later in my code to fail ( even when I remove all other code references to bisal except the import statement)

**Pull request closed without merging**
