### PR TITLE
ENH Make transforms batch shape agnostic (2D)

### LINKED ISSUE #218: Make inputs dimension-agnostic (1D/2D)
In other words, make `Scattering*D` operators act only on last dimension without forcing a specific convention on previous dimensions. The output would have the same shape, but this the time/spatial dimension subsampled and another (scattering) dimension added right before it. So we'd have

- in 1D, `batch_shape + (T,)` input gives `batch_shape + (C, T/2**J)` output, and
- in 2D, `batch_shape + (N, M)` input gives `batch_shape + (C, N/2**J, M/2**J)` output,

where `batch_shape` is some (possibly empty) tuple specifying the batch dimensions that are not to be processed and `C` is the number of scattering coefficients.

The 3D case is more complicated since it follows a different output schema compared to the 1D and 2D, which will be addressed in a separate issue. That being said, it would be good if it could mimic the above behavior.

### PR DESCRIPTION
**Pull request by janden**
See #221. Fixes #218.

### CODE REVIEW

**Comment by janden** [comment]
If I don't hear anything by tomorrow, I will merge this.

**Comment by lostanlen** [comment]
This looks good to me. I suppose that the `reshape`s do not produce copies?

**Comment by janden** [comment]
> This looks good to me. I suppose that the `reshape`s do not produce copies?

They do, if necessary. See https://github.com/kymatio/kymatio/pull/221/files/73942eb4adc6e4d42615865ac0c59119f7569804#r238076672. @eickenberg says we should prefer it to `view()` for compatibility purposes.

**Comment by lostanlen** [comment]
Ok. Let's merge this. If we can make it faster / less memory-intensive in the future, we can always refine further without breaking the API.

**Comment by janden** [comment]
> Ok. Let's merge this. 

Ok good. Want to get input from some 2D people as well before going ahead. @edouardoyallon?

> If we can make it faster / less memory-intensive in the future, we can always refine further without breaking the API.

You mean removing the `reshape()`s to avoid copies? I don't think that's going to be possible. There are other places in the code that requires the arrays to be contiguous (e.g., the `skcuda` backend), I think, so if no copy is made here, a copy will be made there.

**Comment by eickenberg** [comment]
This looks great to me. Thanks!

**Pull request merged**
