### PR TITLE
REF Homogenize 3d output

### LINKED ISSUE #222: 3D output format
Currently, `Scattering3D` takes an input of shape `(B, M, N, O)`, where `B` is the batch size and `M, N, O` is the shape of the input signal. Depending on `method`, the output takes different formats:

- If `method='standard'`, the output is of shape `(B, 2*M*N*O, total_scales, L+1)`, where `total_scales` is the number of scales at all orders, that is `(J+1)+J*(J+1)/2` if `order_2=True`. The factor `2` in the second axis comes from the fact that these are still stored as "complex" values (even though they are real), so every other element along that axis is zero. These zeroes should probably be eliminated.
- If `method='integral'`, the output is of shape `(B, len(integral_powers), total_scales, L+1)`, where `integral_powers` is the argument provided to `forward()`.
- If `method='local'`, the output is of shape `(B, points.shape[1], total_scales, L+1)`, where `points` is the argument provided to `forward()`.

The first question is whether we should provide all these outputs through the same interface. To a certain extent, `'integral'` and `'local'` can be computed from `'standard'`, but this may not be computationally optimal.

The second question is how to structure these outputs to be more consistent with 1D and 2D. I suggest that we adopt a similar output shape `(B, C, M, N, O)`, where the second axis comingles orders, scales, ells, integral powers, and points, as the case may be. Alternatively, for `'integral`' and `'local'`, the third axis could index `integral_powers` or `points` instead of a singleton spatial dimension.

### PR DESCRIPTION
**Pull request by eickenberg**
This doesn't work yet. I have refactored the `standard` output so that it doesn't ravel, but my brain is in a state where I can't get the test data reshaped correctly to make the test pass.

This is the last thing we need to fix before being able to release

[EDIT by @lostanlen: closes #222]

### CODE REVIEW

**Comment by janden** [comment]
I can take a look at this tonight, but a quick fix is to recalculate the test data and save it do the `test_data_3d.pt` file. It's up to you.

**Comment by janden** [comment]
(we're talking ETA 6-8 hours)

**Comment by janden** [comment]
So the tests are ok now. I also corrected (?) a small bug in order 1 since it was giving a different ordering there. If everything looks good, let's merge!

**Comment by eickenberg** [comment]
Yeah this does look good now! Thanks @janden for fixing the tests and the 1D part!!

**Comment by eickenberg** [comment]
Going to squash because of the test

**Pull request merged**
