### PR TITLE
save kymatio configuration as a keras-compatible dict

### LINKED ISSUE #637: Keras not saving model architecture
**Hi everybody, 
I have included in a Keras model a scattering layer using the following syntax:**

```
import kymatio
from kymatio.keras import Scattering2D

# Model architecture
def Dual_ResNet_Atrous_Att_WST(input_shape=(HEIGHT, WIDTH, CHANNELS),
                   mra_channels=MRACHANNELS,
                   num_class=NUM_CLASS,
                   ks1=KS1, ks2=KS2, ks3=KS3, 
                   dl1=DL1, dl2=DL2, dl3=DL3,
                   filters=NF,resblock1=NR1,
                   r_filters=NFL, resblock2=NR2,
                   dil_mode=DIL_MODE, 
                   sp_dropout=DR1,re_dropout=DR2,
                   mask_float=True,
                   attention=None,
                   mask_threshold=0.5,
                   return_seq=True):

    input_1 = Input(shape=(input_shape[0],input_shape[1],mra_channels))    
    input_2 = Input(shape=input_shape)
    input_3 = tf.where(tf.greater(input_2,mask_threshold),1.0,0.0)
    
    if attention == 'wst':
        # wavelet scattering transform (WST)
        d01 = UpSampling2D(size=(4, 4), interpolation="bilinear")(input_1)
        d02 = Lambda(lambda x: x[:,:,:,0])(d01)
        d03 = Scattering2D(J=2,L=6)(d02)
        d0 = tf.transpose(d03,perm=[0, 2, 3, 1])
    
    for cycle in range(resblock1):
        if cycle == 0:            
            d1 = stem_split_3k(d0, filters, mode=dil_mode, 
                                kernel_size_1=ks1, kernel_size_2=ks2, kernel_size_3=ks3, 
                                dilation_1=dl1, dilation_2=dl2, dilation_3=dl3,
                                kernel_regularizer=None)                      
        else:
            d1 = residual_block_split_3k(d1, filters, mode=dil_mode, 
                                         kernel_size_1=ks1, kernel_size_2=ks2, kernel_size_3=ks3, 
                                         dilation_1=dl1, dilation_2=dl2, dilation_3=dl3,
                                         kernel_regularizer=None) 
            

        d1 = SpatialDropout2D(sp_dropout)(d1)            
                 
    d2 = residual_block_split_3k(d1, num_class, mode="add", 
                                    kernel_size_1=ks1, kernel_size_2=ks2, kernel_size_3=ks3, 
                                    dilation_1=dl1, dilation_2=dl2,dilation_3=dl3,
                                    kernel_regularizer=regularizers.l1_l2(l1=1e-5, l2=1e-4))
        
    d3 = LeakyReLU(alpha=0.1)(d2)
    
    if mask_float:
        d3 = Multiply()([d3, input_2])
    else:
        d3 = Multiply()([d3, input_3])
   
    d3 = GlobalAveragePooling2D()(d3)    
    
    output_1 = Activation("softmax", name = 'softmax')(d3)    
    
    model = Model([input_1,input_2], output_1, name='Dual_Res-CR-Net_Att_WST')    

    return model

```

 **The model compiles without problems:**

```
# Model compilation
strategy = tf.distribute.MirroredStrategy()
with strategy.scope():
    model = Dual_ResNet_Atrous_Att_WST(input_shape=(HEIGHT, WIDTH, CHANNELS),
                   mra_channels=MRACHANNELS,                          
                   num_class=NUM_CLASS,
                   ks1=KS1, ks2=KS2, ks3=KS3, 
                   dl1=DL1, dl2=DL2, dl3=DL3,
                   filters=NF,resblock1=NR1,
                   r_filters=NFL, resblock2=NR2,
                   dil_mode=DIL_MODE, 
                   sp_dropout=DR1,re_dropout=DR2,
                   mask_float=True,
                   attention='wst',
                   mask_threshold=0.5,                                         
                   return_seq=True)
        
    model.compile(optimizer=Adam(), 
                      loss=tf.keras.losses.CategoricalCrossentropy(), 
                      metrics=[tf.keras.metrics.CategoricalAccuracy()])

model.summary()
```

Model: Dual_Res-CR-Net_Att_WST

input_1 (InputLayer)            [(None, 300, 340, 1) 0                                            
__________________________________________________________________________________________________
up_sampling2d (UpSampling2D)    (None, 1200, 1360, 1 0           input_1[0][0]                    
__________________________________________________________________________________________________
lambda (Lambda)                 (None, 1200, 1360)   0           up_sampling2d[0][0]              
__________________________________________________________________________________________________
scattering2d (Scattering2D)     (None, 49, 300, 340) 0           lambda[0][0]                     
__________________________________________________________________________________________________
tf_op_layer_transpose (TensorFl [(None, 300, 340, 49 0           scattering2d[0][0]               
__________________________________________________________________________________________________
separable_conv2d (SeparableConv (None, 300, 340, 16) 1241        tf_op_layer_transpose[0][0]      
__________________________________________________________________________________________________
separable_conv2d_2 (SeparableCo (None, 300, 340, 16) 2025        tf_op_layer_transpose[0][0]      
__________________________________________________________________________________________________
separable_conv2d_4 (SeparableCo (None, 300, 340, 16) 3201        tf_op_layer_transpose[0][0]      
__________________________________________________________________________________________________
batch_normalization (BatchNorma (None, 300, 340, 16) 64          separable_conv2d[0][0]           
__________________________________________________________________________________________________
batch_normalization_1 (BatchNor (None, 300, 340, 16) 64          separable_conv2d_2[0][0]         
__________________________________________________________________________________________________
batch_normalization_2 (BatchNor (None, 300, 340, 16) 64          separable_conv2d_4[0][0]         
__________________________________________________________________________________________________
leaky_re_lu (LeakyReLU)         (None, 300, 340, 16) 0           batch_normalization[0][0]        
__________________________________________________________________________________________________
leaky_re_lu_1 (LeakyReLU)       (None, 300, 340, 16) 0           batch_normalization_1[0][0]      
__________________________________________________________________________________________________
leaky_re_lu_2 (LeakyReLU)       (None, 300, 340, 16) 0           batch_normalization_2[0][0]      
__________________________________________________________________________________________________
conv2d (Conv2D)                 (None, 300, 340, 48) 2400        tf_op_layer_transpose[0][0]      
__________________________________________________________________________________________________
separable_conv2d_1 (SeparableCo (None, 300, 340, 16) 416         leaky_re_lu[0][0]                
__________________________________________________________________________________________________
separable_conv2d_3 (SeparableCo (None, 300, 340, 16) 672         leaky_re_lu_1[0][0]              
__________________________________________________________________________________________________
separable_conv2d_5 (SeparableCo (None, 300, 340, 16) 1056        leaky_re_lu_2[0][0]              
__________________________________________________________________________________________________
batch_normalization_3 (BatchNor (None, 300, 340, 48) 192         conv2d[0][0]                     
__________________________________________________________________________________________________
concatenate (Concatenate)       (None, 300, 340, 48) 0           separable_conv2d_1[0][0]         
                                                                 separable_conv2d_3[0][0]         
                                                                 separable_conv2d_5[0][0]         
__________________________________________________________________________________________________
add (Add)                       (None, 300, 340, 48) 0           batch_normalization_3[0][0]      
                                                                 concatenate[0][0]                
__________________________________________________________________________________________________
spatial_dropout2d (SpatialDropo (None, 300, 340, 48) 0           add[0][0]                        
__________________________________________________________________________________________________
batch_normalization_4 (BatchNor (None, 300, 340, 48) 192         spatial_dropout2d[0][0]          
__________________________________________________________________________________________________
leaky_re_lu_3 (LeakyReLU)       (None, 300, 340, 48) 0           batch_normalization_4[0][0]      
__________________________________________________________________________________________________
separable_conv2d_6 (SeparableCo (None, 300, 340, 16) 1216        leaky_re_lu_3[0][0]              
__________________________________________________________________________________________________
separable_conv2d_8 (SeparableCo (None, 300, 340, 16) 1984        leaky_re_lu_3[0][0]              
__________________________________________________________________________________________________
separable_conv2d_10 (SeparableC (None, 300, 340, 16) 3136        leaky_re_lu_3[0][0]              
__________________________________________________________________________________________________
batch_normalization_5 (BatchNor (None, 300, 340, 16) 64          separable_conv2d_6[0][0]         
__________________________________________________________________________________________________
batch_normalization_6 (BatchNor (None, 300, 340, 16) 64          separable_conv2d_8[0][0]         
__________________________________________________________________________________________________
batch_normalization_7 (BatchNor (None, 300, 340, 16) 64          separable_conv2d_10[0][0]        
__________________________________________________________________________________________________
leaky_re_lu_4 (LeakyReLU)       (None, 300, 340, 16) 0           batch_normalization_5[0][0]      
__________________________________________________________________________________________________
leaky_re_lu_5 (LeakyReLU)       (None, 300, 340, 16) 0           batch_normalization_6[0][0]      
__________________________________________________________________________________________________
leaky_re_lu_6 (LeakyReLU)       (None, 300, 340, 16) 0           batch_normalization_7[0][0]      
__________________________________________________________________________________________________
conv2d_1 (Conv2D)               (None, 300, 340, 48) 2352        spatial_dropout2d[0][0]          
__________________________________________________________________________________________________
separable_conv2d_7 (SeparableCo (None, 300, 340, 16) 416         leaky_re_lu_4[0][0]              
__________________________________________________________________________________________________
separable_conv2d_9 (SeparableCo (None, 300, 340, 16) 672         leaky_re_lu_5[0][0]              
__________________________________________________________________________________________________
separable_conv2d_11 (SeparableC (None, 300, 340, 16) 1056        leaky_re_lu_6[0][0]              
__________________________________________________________________________________________________
batch_normalization_8 (BatchNor (None, 300, 340, 48) 192         conv2d_1[0][0]                   
__________________________________________________________________________________________________
concatenate_1 (Concatenate)     (None, 300, 340, 48) 0           separable_conv2d_7[0][0]         
                                                                 separable_conv2d_9[0][0]         
                                                                 separable_conv2d_11[0][0]        
__________________________________________________________________________________________________
add_1 (Add)                     (None, 300, 340, 48) 0           batch_normalization_8[0][0]      
                                                                 concatenate_1[0][0]              
__________________________________________________________________________________________________
spatial_dropout2d_1 (SpatialDro (None, 300, 340, 48) 0           add_1[0][0]                      
__________________________________________________________________________________________________
batch_normalization_9 (BatchNor (None, 300, 340, 48) 192         spatial_dropout2d_1[0][0]        
__________________________________________________________________________________________________
leaky_re_lu_7 (LeakyReLU)       (None, 300, 340, 48) 0           batch_normalization_9[0][0]      
__________________________________________________________________________________________________
separable_conv2d_12 (SeparableC (None, 300, 340, 2)  530         leaky_re_lu_7[0][0]              
__________________________________________________________________________________________________
separable_conv2d_14 (SeparableC (None, 300, 340, 2)  1298        leaky_re_lu_7[0][0]              
__________________________________________________________________________________________________
separable_conv2d_16 (SeparableC (None, 300, 340, 2)  2450        leaky_re_lu_7[0][0]              
__________________________________________________________________________________________________
batch_normalization_10 (BatchNo (None, 300, 340, 2)  8           separable_conv2d_12[0][0]        
__________________________________________________________________________________________________
batch_normalization_11 (BatchNo (None, 300, 340, 2)  8           separable_conv2d_14[0][0]        
__________________________________________________________________________________________________
batch_normalization_12 (BatchNo (None, 300, 340, 2)  8           separable_conv2d_16[0][0]        
__________________________________________________________________________________________________
conv2d_2 (Conv2D)               (None, 300, 340, 2)  98          spatial_dropout2d_1[0][0]        
__________________________________________________________________________________________________
leaky_re_lu_8 (LeakyReLU)       (None, 300, 340, 2)  0           batch_normalization_10[0][0]     
__________________________________________________________________________________________________
leaky_re_lu_9 (LeakyReLU)       (None, 300, 340, 2)  0           batch_normalization_11[0][0]     
__________________________________________________________________________________________________
leaky_re_lu_10 (LeakyReLU)      (None, 300, 340, 2)  0           batch_normalization_12[0][0]     
__________________________________________________________________________________________________
batch_normalization_13 (BatchNo (None, 300, 340, 2)  8           conv2d_2[0][0]                   
__________________________________________________________________________________________________
separable_conv2d_13 (SeparableC (None, 300, 340, 2)  24          leaky_re_lu_8[0][0]              
__________________________________________________________________________________________________
separable_conv2d_15 (SeparableC (None, 300, 340, 2)  56          leaky_re_lu_9[0][0]              
__________________________________________________________________________________________________
separable_conv2d_17 (SeparableC (None, 300, 340, 2)  104         leaky_re_lu_10[0][0]             
__________________________________________________________________________________________________
add_2 (Add)                     (None, 300, 340, 2)  0           batch_normalization_13[0][0]     
                                                                 separable_conv2d_13[0][0]        
                                                                 separable_conv2d_15[0][0]        
                                                                 separable_conv2d_17[0][0]        
__________________________________________________________________________________________________
leaky_re_lu_11 (LeakyReLU)      (None, 300, 340, 2)  0           add_2[0][0]  
__________________________________________________________________________________________________                    
input_2 (InputLayer)            [(None, 300, 340, 1) 0 
__________________________________________________________________________________________________                                           
multiply (Multiply)             (None, 300, 340, 2)  0           leaky_re_lu_11[0][0]             
                                                                 input_2[0][0] 
__________________________________________________________________________________________________                   
global_average_pooling2d (Globa (None, 2)            0           multiply[0][0] 
__________________________________________________________________________________________________                  
softmax (Activation)            (None, 2)            0           global_average_pooling2d[0][0]  
__________________________________________________________________________________________________ 

Total params: 27,587
Trainable params: 26,995
Non-trainable params: 592

**and runs very nicely and very fast (for example, just 3 epochs), however with a warning for not being able to serialize as JSON and a second warning: Layers with arguments in `__init__` must override `get_config`.**

```
# TRAINING
epoch_num = 3
train_steps = len(train_generator)
val_steps = len(valid_generator)

history = model.fit(train_generator, 
                    validation_data=valid_generator,
                    steps_per_epoch=train_steps,
                    validation_steps=val_steps,
                    epochs=epoch_num,
                    initial_epoch=initial_epoch,
                    max_queue_size =15,
                    workers=1,
                    callbacks = callbacks_list)
```
  
Train for 81 steps, validate for 16 steps
WARNING:tensorflow:Model failed to serialize as JSON. Ignoring... Layers with arguments in `__init__` must override `get_config`.
Epoch 1/3
INFO:tensorflow:batch_all_reduce: 88 all-reduces with algorithm = nccl, num_packs = 1, agg_small_grads_max_bytes = 0 and agg_small_grads_max_group = 10
INFO:tensorflow:batch_all_reduce: 88 all-reduces with algorithm = nccl, num_packs = 1, agg_small_grads_max_bytes = 0 and agg_small_grads_max_group = 10
81/81 [==============================] - 535s 7s/step - loss: 0.1260 - categorical_accuracy: 0.3951 - val_loss: 0.1268 - val_categorical_accuracy: 0.3000
Epoch 2/3
81/81 [==============================] - 146s 2s/step - loss: 0.1206 - categorical_accuracy: 0.3160 - val_loss: 0.1237 - val_categorical_accuracy: 0.3000
Epoch 3/3
81/81 [==============================] - 146s 2s/step - loss: 0.1178 - categorical_accuracy: 0.3185 - val_loss: 0.1192 - val_categorical_accuracy: 0.3000

**However if I try to save the model architecture without weights:**
 
`model.save('models/3_epoch_' + model_selection + '_' + model_number + '_arch' + '.h5')`

**I get:**
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-27-abc9f39fa94f> in <module>
      1 # In[12]:
      2 # Save architecture without weights as h5
----> 3 model.save('models/3_epoch_' + model_selection + '_' + model_number + '_arch' + '.h5')

/wsu/el7/pre-compiled/python/3.7/envs/tensorflow_gpuenv_v2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py in save(self, filepath, overwrite, include_optimizer, save_format, signatures, options)
   1006     """
   1007     save.save_model(self, filepath, overwrite, include_optimizer, save_format,
-> 1008                     signatures, options)
   1009 
   1010   def save_weights(self, filepath, overwrite=True, save_format=None):

/wsu/el7/pre-compiled/python/3.7/envs/tensorflow_gpuenv_v2/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py in save_model(model, filepath, overwrite, include_optimizer, save_format, signatures, options)
    110           'or using `save_weights`.')
    111     hdf5_format.save_model_to_hdf5(
--> 112         model, filepath, overwrite, include_optimizer)
    113   else:
    114     saved_model_save.save(model, filepath, overwrite, include_optimizer,

/wsu/el7/pre-compiled/python/3.7/envs/tensorflow_gpuenv_v2/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py in save_model_to_hdf5(model, filepath, overwrite, include_optimizer)
     97 
     98   try:
---> 99     model_metadata = saving_utils.model_metadata(model, include_optimizer)
    100     for k, v in model_metadata.items():
    101       if isinstance(v, (dict, list, tuple)):

/wsu/el7/pre-compiled/python/3.7/envs/tensorflow_gpuenv_v2/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saving_utils.py in model_metadata(model, include_optimizer, require_config)
    170   except NotImplementedError as e:
    171     if require_config:
--> 172       raise e
    173 
    174   metadata = dict(

/wsu/el7/pre-compiled/python/3.7/envs/tensorflow_gpuenv_v2/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saving_utils.py in model_metadata(model, include_optimizer, require_config)
    167   model_config = {'class_name': model.__class__.__name__}
    168   try:
--> 169     model_config['config'] = model.get_config()
    170   except NotImplementedError as e:
    171     if require_config:

/wsu/el7/pre-compiled/python/3.7/envs/tensorflow_gpuenv_v2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py in get_config(self)
    916     if not self._is_graph_network:
    917       raise NotImplementedError
--> 918     return copy.deepcopy(get_network_config(self))
    919 
    920   @classmethod

/wsu/el7/pre-compiled/python/3.7/envs/tensorflow_gpuenv_v2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py in get_network_config(network, serialize_layer_fn)
   1991           filtered_inbound_nodes.append(node_data)
   1992 
-> 1993     layer_config = serialize_layer_fn(layer)
   1994     layer_config['name'] = layer.name
   1995     layer_config['inbound_nodes'] = filtered_inbound_nodes

/wsu/el7/pre-compiled/python/3.7/envs/tensorflow_gpuenv_v2/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py in serialize_keras_object(instance)
    196 
    197   if hasattr(instance, 'get_config'):
--> 198     config = instance.get_config()
    199     serialization_config = {}
    200     for key, item in config.items():

/wsu/el7/pre-compiled/python/3.7/envs/tensorflow_gpuenv_v2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py in get_config(self)
    497     # or that `get_config` has been overridden:
    498     if len(extra_args) > 1 and hasattr(self.get_config, '_is_default'):
--> 499       raise NotImplementedError('Layers with arguments in `__init__` must '
    500                                 'override `get_config`.')
    501     return config

NotImplementedError: Layers with arguments in `__init__` must override `get_config`.

 
**Alternatively I can try to save the model including the weights:**

```
model.save('models/3_epoch_' + model_selection + '_' + model_number + '_all' + '.h5',
        overwrite=True,include_optimizer=False,save_format='h5',signatures=None,options=None)
```

**in which case I also get:**
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-26-ccabc94d774e> in <module>
      3 # Save architecture + weights
      4 model.save('models/3_epoch_' + model_selection + '_' + model_number + '_all' + '.h5',
----> 5         overwrite=True,include_optimizer=False,save_format='h5',signatures=None,options=None)

/wsu/el7/pre-compiled/python/3.7/envs/tensorflow_gpuenv_v2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py in save(self, filepath, overwrite, include_optimizer, save_format, signatures, options)
   1006     """
   1007     save.save_model(self, filepath, overwrite, include_optimizer, save_format,
-> 1008                     signatures, options)
   1009 
   1010   def save_weights(self, filepath, overwrite=True, save_format=None):

/wsu/el7/pre-compiled/python/3.7/envs/tensorflow_gpuenv_v2/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py in save_model(model, filepath, overwrite, include_optimizer, save_format, signatures, options)
    110           'or using `save_weights`.')
    111     hdf5_format.save_model_to_hdf5(
--> 112         model, filepath, overwrite, include_optimizer)
    113   else:
    114     saved_model_save.save(model, filepath, overwrite, include_optimizer,

/wsu/el7/pre-compiled/python/3.7/envs/tensorflow_gpuenv_v2/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py in save_model_to_hdf5(model, filepath, overwrite, include_optimizer)
     97 
     98   try:
---> 99     model_metadata = saving_utils.model_metadata(model, include_optimizer)
    100     for k, v in model_metadata.items():
    101       if isinstance(v, (dict, list, tuple)):

/wsu/el7/pre-compiled/python/3.7/envs/tensorflow_gpuenv_v2/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saving_utils.py in model_metadata(model, include_optimizer, require_config)
    170   except NotImplementedError as e:
    171     if require_config:
--> 172       raise e
    173 
    174   metadata = dict(

/wsu/el7/pre-compiled/python/3.7/envs/tensorflow_gpuenv_v2/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saving_utils.py in model_metadata(model, include_optimizer, require_config)
    167   model_config = {'class_name': model.__class__.__name__}
    168   try:
--> 169     model_config['config'] = model.get_config()
    170   except NotImplementedError as e:
    171     if require_config:

/wsu/el7/pre-compiled/python/3.7/envs/tensorflow_gpuenv_v2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py in get_config(self)
    916     if not self._is_graph_network:
    917       raise NotImplementedError
--> 918     return copy.deepcopy(get_network_config(self))
    919 
    920   @classmethod

/wsu/el7/pre-compiled/python/3.7/envs/tensorflow_gpuenv_v2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py in get_network_config(network, serialize_layer_fn)
   1991           filtered_inbound_nodes.append(node_data)
   1992 
-> 1993     layer_config = serialize_layer_fn(layer)
   1994     layer_config['name'] = layer.name
   1995     layer_config['inbound_nodes'] = filtered_inbound_nodes

/wsu/el7/pre-compiled/python/3.7/envs/tensorflow_gpuenv_v2/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py in serialize_keras_object(instance)
    196 
    197   if hasattr(instance, 'get_config'):
--> 198     config = instance.get_config()
    199     serialization_config = {}
    200     for key, item in config.items():

/wsu/el7/pre-compiled/python/3.7/envs/tensorflow_gpuenv_v2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py in get_config(self)
    497     # or that `get_config` has been overridden:
    498     if len(extra_args) > 1 and hasattr(self.get_config, '_is_default'):
--> 499       raise NotImplementedError('Layers with arguments in `__init__` must '
    500                                 'override `get_config`.')
    501     return config

NotImplementedError: Layers with arguments in `__init__` must override `get_config`.

**In both cases a .h5 file is made, but if I try to reload the model from either saved .h5, the loaded file does not contain a model.:**

```
strategy = tf.distribute.MirroredStrategy()
with strategy.scope():

    filepath = 'models/' + model_selection + '_' + model_number + '.h5'    
    model = load_model(filepath, compile=False)     

    model.compile(optimizer=Adam(), 
                  loss=tf.keras.losses.CategoricalCrossentropy(), 
                  metrics=[tf.keras.metrics.CategoricalAccuracy()])
```
 
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1')

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-32-1a023ca8bc9a> in <module>
      5     # filepath = 'models/' + model_selection + '_' + model_number + '_all' + '.h5'
      6     filepath = 'models/' + model_selection + '_' + model_number + '.h5'
----> 7     model = load_model(filepath, compile=False)
      8 
      9     model.compile(optimizer=Adam(), 

/wsu/el7/pre-compiled/python/3.7/envs/tensorflow_gpuenv_v2/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py in load_model(filepath, custom_objects, compile)
    144   if (h5py is not None and (
    145       isinstance(filepath, h5py.File) or h5py.is_hdf5(filepath))):
--> 146     return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
    147 
    148   if isinstance(filepath, six.string_types):

/wsu/el7/pre-compiled/python/3.7/envs/tensorflow_gpuenv_v2/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py in load_model_from_hdf5(filepath, custom_objects, compile)
    163     model_config = f.attrs.get('model_config')
    164     if model_config is None:
--> 165       raise ValueError('No model found in config file.')
    166     model_config = json.loads(model_config.decode('utf-8'))
    167     model = model_config_lib.model_from_config(model_config,

ValueError: No model found in config file.

**Saving as JSON or tensorflow _savedmodel_ format are equally ineffective. At this time the only fix I can find in order to be able to use a pretrained model, is to save only the weights:**

`model.save_weights('models/3_epoch_' + model_selection + '_' + model_number + '_weights' + '.h5')`

**then recompile the model from scratch and load the saved weights:**

```
strategy = tf.distribute.MirroredStrategy()
with strategy.scope():

    model = Dual_ResNet_Atrous_Att_WST(input_shape=(HEIGHT, WIDTH, CHANNELS),
               mra_channels=MRACHANNELS,                          
               num_class=NUM_CLASS,
               ks1=KS1, ks2=KS2, ks3=KS3, 
               dl1=DL1, dl2=DL2, dl3=DL3,
               filters=NF,resblock1=NR1,
               r_filters=NFL, resblock2=NR2,
               dil_mode=DIL_MODE, 
               sp_dropout=DR1,re_dropout=DR2,
               mask_float=True,
               attention='wst',
               mask_threshold=0.5,                                         
               return_seq=True)

    model.compile(optimizer=Adam(), 
                  loss=tf.keras.losses.CategoricalCrossentropy(), 
                  metrics=[tf.keras.metrics.CategoricalAccuracy()])          

model.load_weights('models/best_' + model_selection + '_' + model_number + '_weights.h5') 

```

### PR DESCRIPTION
**Pull request by lostanlen**
Fixes #637

### CODE REVIEW

**Comment by lostanlen** [comment]
not sure if i should PR into master or dev ?

**Comment by eickenberg** [comment]
OK so this seems to be not properly rebased on `dev`. It looks like you started from master?

There would be good reason to merge this into master since it is a bugfix, but we would want to have it in dev as well. I'm sure rebasing dev on master should work later on after these changes, so in that sense master sounds like the best choice.

The only actual changes you made were to add `get_config` and test it, right? (all the other changes come from the rebasing issue I mean)

**Review by eickenberg — APPROVED** [review]
This LGTM for merge into master. What do you think @janden ?

**Comment by janden** [comment]
Eh it all depends on how long we expect 0.3 to take. Will we cut 0.2.1 in the meantime?

**Comment by edouardoyallon** [comment]
some people might be relying on 2.x and this is a bug of 2.x. Thus...

**Comment by janden** [comment]
Right I see. Let's merge to master, then. @lostanlen Can you clean up the history? There also seems to be a bug introduced in test_keras_scattering2d.py that needs to be fixed (`sc` → `scat`).

Since we're on the subject of bugfixes, we should also fix the issues relating to cupy (https://github.com/kymatio/kymatio/commit/844cd5614bd986ff3086910e0af20b91b18f0fa0). It might make sense to cherry-pick that one on top of master and make another PR, merge that, then rebase this one and see if the tests pass again.

**Comment by lostanlen** [comment]
@janden understood, will do

**Comment by janden** [comment]
What's happening here?

**Comment by lostanlen** [comment]
@janden a tragedy: i volunteer for fixing an issue, write six lines of code, am told i should clean up the history, attempts to change branch. chaos ensues

**Comment by janden** [comment]
All right. So what's the plan? It should be possible to start over from dev and cherry-pick the last two (?) commits to recreate the PR.

**Comment by edouardoyallon** [comment]
Why did it get closed? is it fixed?

**Comment by janden** [comment]
So I think this can be closed in light of #670?

**Comment by edouardoyallon** [comment]
> So I think this can be closed in light of #670?

OK!

**Pull request closed without merging**
