### PR TITLE
MAINT redefine cdgmm3d to call cdgmm in torch skcuda backend

### PR DESCRIPTION
**Pull request by MuawizChaudhary**
This pull request redefines cdgmm3d to call cdgmm in torch skcuda backend. 

I'm also using this as a proxy for testing the torch_skcuda 3d backend.

### CODE REVIEW

**Comment by lostanlen** [comment]
is this tied to a specific issue? what's the plan here?

**Comment by MuawizChaudhary** [comment]
my reasoning: why are we repeating code that we already have?

**Comment by lostanlen** [comment]
oh wow, we have duplicate code here? then yes sounds like an easy win

**Comment by lostanlen** [comment]
is the change from a `RuntimeError` to a `TypeError` harmless here?

**Comment by MuawizChaudhary** [comment]
define harmless? 

I changed it because it seemed like we forgot to switch the 3d cgmm over to throwing a [Type Error when we changed the 1d and 2d code to be unified](https://github.com/kymatio/kymatio/commit/69f132af14b1108ba70ae3ac9c945e4b0bb913b0)

**Comment by MuawizChaudhary** [comment]
> > my reasoning: why are we repeating code that we already have?
> 
> Maybe there was a reason for having a separate `cdgmm3d`? On the other hand, the tests pass…

The code is the same except for the error checking.

**Comment by janden** [comment]
Ok sounds good then.

**Review by janden — APPROVED** [review]

**Pull request merged**
