### PR TITLE
TST Try GH actions for pip tests

### PR DESCRIPTION
**Pull request by janden**
Adds configuration files for two workflows: one for pip install and one for conda install. Ideally, it should just pop up as a check in the PR, but we'll see.

### CODE REVIEW

**Comment by janden** [comment]
@edouardoyallon @eickenberg If this looks good to you, I suggest we merge it ASAP to get the GH Actions CI working for the other PRs.

**Comment by eickenberg** [comment]
This is great. Thanks for setting this up!

Is there any way we can test over several pytorch versions?

If that is not straight-forward, let's just merge this in, because it's orthogonal to everything else

**Comment by eickenberg** [comment]
Is merging into dev useful here? Will the github actions be triggered on that already or do we need to merge into master?

**Review by eickenberg — APPROVED** [review]
approved

**Comment by janden** [comment]
> Is there any way we can test over several pytorch versions?

Yes but this takes more time, obviously, since we have limited capacity. My vote would be to remove the conda tests, but we can discuss that later. Another possibility is if we could have more tests run in parallel, which might be relevant once we get self-hosted runners going on @edouardoyallon's machine.

> Is merging into dev useful here? Will the github actions be triggered on that already or do we need to merge into master?

I don't know. We're about to find out. They show up on my fork: https://github.com/janden/kymatio/pull/3

**Pull request merged**
