### PR TITLE
TST Fix GHA issues

### PR DESCRIPTION
**Pull request by janden**
Instead of system conda.

### CODE REVIEW

**Review by edouardoyallon — APPROVED** [review]
(no idea what i'm looking at)

**Comment by eickenberg** [comment]
> (no idea what i'm looking at)

lol me neither. was this working at some point without the bin and now it requires it?

**Comment by janden** [comment]
Whoa calm down people. It's a draft. Stay tuned for the rest of the story…

**Comment by janden** [comment]
So I think I solved the issue with pip. Had to do with the fact that `1.7.1 > 1.7` so it assumed it could run the new FFT interface on `1.7.1`. I'm still a little concerned about this conda envrionment naming stuff -- ideally if the runners keep their own versions of conda, there shouldn't be any conflict.

At any rate, GHA is currently out of commission (https://www.githubstatus.com/incidents/s654n76c1bwr) so we won't find out until tomorrow.

**Comment by janden** [comment]
Ok done now. Everything should work.

I still think we should get rid of this `torch17_skcuda` business.

**Comment by edouardoyallon** [comment]
> Ok done now. Everything should work.
> 
> I still think we should get rid of this `torch17_skcuda` business.

alright

**Comment by edouardoyallon** [comment]
Should I merge? I'll prepare a backend that picks torch version.

**Comment by janden** [comment]
> Should I merge?

If everything looks good, yes.

> I'll prepare a backend that picks torch version.

Cool. When looking at the docs, I noticed that the examples fail when running torch 1.7, so it would fix that bug too.

**Comment by janden** [comment]
This should probably be merged soon, assuming everything looks good to you @edouardoyallon @eickenberg.

**Review by edouardoyallon — APPROVED** [review]
I see. The first branch I reviewed was based on this one. Please merge this one and then the other!

**Pull request merged**
