### PR TITLE
ENH Pytorch 1D Back/Frontend [4]

### PR DESCRIPTION
**Pull request by MuawizChaudhary**
Here are the files for the 1d pytorch front and backend.

Recommended to be merged 3rd/4th/5th. Since this is the 1d branch, let's do this 3rd?

### CODE REVIEW

**Comment by edouardoyallon** [comment]
I propose to manipulate this PR when the 2D's PR will be done.

**Comment by MuawizChaudhary** [comment]
I will redo this PR soon! Expect something tomorrow.

**Comment by janden** [comment]
> I propose to manipulate this PR when the 2D's PR will be done.

Yes.

**Comment by edouardoyallon** [comment]
Let's start this PR @MuawizChaudhary @janden

**Comment by janden** [comment]
> Let's start this PR @MuawizChaudhary @janden

Before 2D TF is done?

**Comment by lostanlen** [comment]
are you requesting a code review for this right now or later?

**Comment by MuawizChaudhary** [comment]
> are you requesting a code review for this right now or later?

I'd recommend not reviewing the current code. This branch does not make use of the base scattering class.

I'll redo the PR starting when we get done with the 2D NumPy. Expect something while/after we review the TF code for the 2D.

**Comment by lostanlen** [comment]
OK, thanks for clarifying. In this case, i am removing the requests for CR. Feel free to re-open those requests when the PR is ready.
Bon courage!

**Comment by edouardoyallon** [comment]
It's time to move to this one!

**Pull request closed without merging**
