### PR TITLE
Multi GPU kymatio

### PR DESCRIPTION
**Pull request by anakin-datawalker**
Small changes for multi GPU. Tested on cifar.py function.

Seems to work 90% of the time for 2 GPUs, roughly 20-30% for 4 GPUs. Otherwise segmentation fault.

### CODE REVIEW

**Comment by lostanlen** [comment]
thanks! how come we observe such a big decrease in test coverage?

**Comment by anakin-datawalker** [comment]
It seems to be coming from files not affected by the pull request so no idea why such change has occurred...

**Comment by edouardoyallon** [comment]
@janden is the GPU server from the FI down?

**Comment by edouardoyallon** [comment]
for working on this one, we need a travis script running in a multi gpu setting, @janden thoughts?

**Comment by edouardoyallon** [comment]
given my msg in the issue, this can't work!

**Pull request closed without merging**
