### PR TITLE
WIP adding slurm to gha to avoid anoying colleagues

### PR DESCRIPTION
**Pull request by edouardoyallon**

### CODE REVIEW

**Comment by janden** [comment]
Draft?

**Comment by edouardoyallon** [comment]
> Draft?

yes. I promess it will be done soon. I'm just a bit overwhelmed those days.

**Comment by lostanlen** [comment]
bon courage @edouardoyallon 🙌🏻

**Comment by janden** [comment]
> yes. I promess it will be done soon. I'm just a bit overwhelmed those days.

No rush. Just wanted to make sure we weren't supposed to review it right now.

**Pull request closed without merging**
