### PR TITLE
DEMO slurm

### PR DESCRIPTION
**Pull request by edouardoyallon**
TODO:
- [x] running one unit-test on slurm
- [x] if the job is cancel by gha, use scancel (more extensive tests to do, i ain't sure of the behavior yet..)
- [x] display the output (err and out) of a given job
- [x] fail if the job has failed during its execution

### CODE REVIEW

**Comment by edouardoyallon** [comment]
I'm not sure how to solve it but an issue is that anconda takes about 32G

**Comment by OverLordGoldDragon** [comment]
This is to monitor resource usage, if I understand correctly?

**Comment by janden** [comment]
What's the status on this?

**Comment by edouardoyallon** [comment]
Tests seem good, should this be closed?

**Pull request closed without merging**
