### PR TITLE
BUG Is the prototype of the function correct?

### LINKED ISSUE #300: TST `backward` for complex modulus is not tested
Specifically, codecov reports that [lines 90-105](https://github.com/kymatio/kymatio/blob/master/kymatio/scattering1d/backend/backend_torch.py#L90) of `backend_torch.py` are [never executed](https://codecov.io/gh/kymatio/kymatio/src/master/kymatio/scattering1d/backend/backend_torch.py#L90). This is odd because we specifically test the `backward` function in the [corresponding test](https://github.com/kymatio/kymatio/blob/master/kymatio/scattering1d/tests/test_utils.py#L87). Somehow, torch must be bypassing our code.

### PR DESCRIPTION
**Pull request by edouardoyallon**
Attempt to Fix #300!

### CODE REVIEW

**Comment by janden** [comment]
Huh? That's it?

**Comment by edouardoyallon** [comment]
> Huh? That's it?

Well, travis gonna tell... I do not got any travis on my own😺

**Comment by janden** [comment]
Looks like that's a nyet...

**Comment by edouardoyallon** [comment]
lol

**Comment by edouardoyallon** [comment]
@johmathe any ideas?

**Comment by eickenberg** [comment]
Just for me to understand:
In the travis log, I find this `assert 1==0` to raise an error https://travis-ci.org/kymatio/kymatio/jobs/500440735#L656

So this means that the code was actually executed, right?
And means that Jenkins is being weird?

**Comment by edouardoyallon** [comment]
> So this means that the code was actually executed, right?
> And means that codecov is being weird?

The answer is positive for both questions.

**Comment by janden** [comment]
I suggest we close this and move the discussion to #300.

**Pull request closed without merging**
