### PR TITLE
ENH adding ens & fi logos

### LINKED ISSUE #353: ENH adding universities' logo which provide resources
Should be added on the main website of kymatio and probably in the README

### PR DESCRIPTION
**Pull request by edouardoyallon**
close #353

### CODE REVIEW

**Comment by janden** [comment]
That FI logo is huge... Must be some way to scale this down.

Also, we need to clear this with FI and ENS. I'm pretty sure there are policies around sticking logos on things that are not slides/posters.

**Comment by edouardoyallon** [comment]
@tomas-angles any suggestions for the ENS-side?  👍 thanks!!

**Comment by janden** [comment]
Ok. Checked with communications here and that's the phrasing/logo they want us to use.

**Comment by eickenberg** [comment]
Viewable here https://github.com/edouardoyallon/kymatio/tree/logos

And looks great to me

**Comment by edouardoyallon** [comment]
someone from ENS needs to confirm this PR.. and then merge!

**Comment by edouardoyallon** [comment]
ENS said yes!

**Pull request merged**
