### PR TITLE
Fix dev (smaller)

### PR DESCRIPTION
**Pull request by OverLordGoldDragon**

### CODE REVIEW

**Comment by janden** [comment]
Again, please split this into smaller PRs – one per logical change.

**Comment by OverLordGoldDragon** [comment]
This PR drops the trailing dimension for complex numbers. This requires changing modulus and fft. There's nothing more to reduce.

**Comment by eickenberg** [comment]
> This PR drops the trailing dimension for complex numbers. This requires changing modulus and fft. There's nothing more to reduce.

Then let's first release the dev-master rebase. This more fundamental change/cleanup can happen after that release.

**Comment by janden** [comment]
Ok so it's only (1) and (2) from #746? Will take a look then.

**Comment by OverLordGoldDragon** [comment]
1 2 and 3, but turns out 3 is nothing new and torch docs were wrong.

**Comment by OverLordGoldDragon** [comment]
I broke this one

**Pull request closed without merging**
