### PR TITLE
Move `pad` from `core` to `base_frontend`

### LINKED ISSUE #852: Unnecessary arguments in `core/scattering1d/scattering1d`
Not a big priority, but an easy simplification. The current prototype of `scattering` is: (phew!)

```python
scattering1d(x, pad, unpad, backend, log2_T, psi1, psi2, phi, pad_left=0,
        pad_right=0, ind_start=None, ind_end=None, oversampling=0,
        max_order=2, average=True, vectorize=False, out_type='array')
```

This didn't come to my attention while reviewing #673 , but the 5th input parameter, `log2_T`, is unnecessary: it is already available as `phi["j"]`. So we could just remove it, and put `log2_T = phi["j"]` at the top of the function.

Thoughts?

### PR DESCRIPTION
**Pull request by lostanlen**
segue of #877, and moves further in the direction of #855 which closed #852
remove pad from core scattering1d

backwards compatible. opens the door towards custom padding in 1d (#859)
no additional tests
contributes to #735

### CODE REVIEW

**Comment by MuawizChaudhary** [comment]
Temporarily setting this to a draft.

**Comment by lostanlen** [comment]
@MuawizChaudhary can we reconsider this now?

**Comment by MuawizChaudhary** [comment]
> @MuawizChaudhary can we reconsider this now?

oui @lostanlen . can u fix the merge conflicts?

**Review by MuawizChaudhary — APPROVED** [review]
Look good to me. I'd merge, but appears there are conflicts/the previous pr (#877  commits show up? )

**Comment by MuawizChaudhary** [comment]
@cyrusvahidi I trust you to merge this once @lostanlen has finished resolving conflicts

**Comment by MuawizChaudhary** [comment]
Closed by #912

**Pull request closed without merging**
