### PR TITLE
DO NOT MERGE Pytorch 2D Back/Frontend

### PR DESCRIPTION
**Pull request by MuawizChaudhary**
Here are the files for the 2d pytorch back and frontend.

Recommended to be merged 3rd/4th/5th.

### CODE REVIEW

**Comment by edouardoyallon** [comment]
Hi, this PR would need some rebasing - I propose todo a squash and merge and to remove external modifications to the doc, etc.

**Comment by janden** [comment]
> Hi, this PR would need some rebasing - I propose todo a squash and merge and to remove external modifications to the doc, etc.

Agreed. There's a lot of stuff in here and it would be good to just have the changes to the 2D frontend/backend that we're interested in.

**Comment by janden** [comment]
I'm not sure what's going on here. The commit history looks very confusing. Is this ready for review?

**Comment by edouardoyallon** [comment]
@janden let's first merge [1] and [2] and let's see the corresponding commit history after while!

**Pull request closed without merging**
