### PR TITLE
Avoid creating unneeded 2D Psi filters

### LINKED ISSUE #314: Unused 2D Psi filters
The generated 2D filterbank includes filters that are not used in the computation.

Let's create a scattering transform:
```
>>> import kymatio
>>> s = kymatio.Scattering2D(J=2, shape=(32, 32))
```

Let's look at the shapes of the generated filters:
```
>>> print("\n".join('{' + ', '.join('%s: %s' % (k, getattr(v, 'shape', v)) for k, v in psi.items()) + '}' for psi in s.Psi))
{j: 0, theta: 0, 0: torch.Size([40, 40, 2])}
{j: 0, theta: 1, 0: torch.Size([40, 40, 2])}
{j: 0, theta: 2, 0: torch.Size([40, 40, 2])}
{j: 0, theta: 3, 0: torch.Size([40, 40, 2])}
{j: 0, theta: 4, 0: torch.Size([40, 40, 2])}
{j: 0, theta: 5, 0: torch.Size([40, 40, 2])}
{j: 0, theta: 6, 0: torch.Size([40, 40, 2])}
{j: 0, theta: 7, 0: torch.Size([40, 40, 2])}
{j: 1, theta: 0, 0: torch.Size([40, 40, 2]), 1: torch.Size([20, 20, 2])}
{j: 1, theta: 1, 0: torch.Size([40, 40, 2]), 1: torch.Size([20, 20, 2])}
{j: 1, theta: 2, 0: torch.Size([40, 40, 2]), 1: torch.Size([20, 20, 2])}
{j: 1, theta: 3, 0: torch.Size([40, 40, 2]), 1: torch.Size([20, 20, 2])}
{j: 1, theta: 4, 0: torch.Size([40, 40, 2]), 1: torch.Size([20, 20, 2])}
{j: 1, theta: 5, 0: torch.Size([40, 40, 2]), 1: torch.Size([20, 20, 2])}
{j: 1, theta: 6, 0: torch.Size([40, 40, 2]), 1: torch.Size([20, 20, 2])}
{j: 1, theta: 7, 0: torch.Size([40, 40, 2]), 1: torch.Size([20, 20, 2])}
```

The 20x20 filters are all unused. Demonstration:
```
>>> for p in s.Psi:
...     if 1 in p:
...        p[1] = 'foo'
...
>>> import torch
>>> x = torch.rand((1, 1, 32, 32)).cuda()
>>> s = s.cuda()
>>> y = s(x)
```

They should probably not be part of the filterbank in the first place?

### PR DESCRIPTION
**Pull request by f0k**
Maybe this fixes #314?

### CODE REVIEW

**Comment by lostanlen** [comment]
yes this looks like it. thanks! could you please write a test that reproduces #314? in principle, that test would fail on the master branch and pass on your branch. once you have that, we'll rebase and merge the PR.

**Comment by f0k** [comment]
I'm also not quite sure how we would test this -- directly reproducing #314 is not an option, I could only check if the total number of tensors matches the expected number, or if there are no filters with a too large resolution index. Ideally, we would check if all tensors participated in the computation, but I'm not sure how? Can we mark all of them as `requires_grad` and check if they are all referenced in the graph that Pytorch builds?

**Comment by janden** [comment]
> if there are no filters with a too large resolution index

I think this would be the way to do it, but again, I don't think we should have a test for this.

> we would check if all tensors participated in the computation

This is a pretty neat idea, and may be possible to do the way you describe it. This could be combined with some sort of benchmark tests (see #259) to ensure that we're not doing something suboptimal (even if it technically works and passes the tests).

**Comment by eickenberg** [comment]
> Ideally, we would check if all tensors participated in the computation, but I'm not sure how? Can we mark all of them as requires_grad and check if they are all referenced in the graph that Pytorch builds?

I think this is a super smart idea, but I wouldn't overthink it: This change seems to have passed the test of transformation output being the correct one, which is the most important one.
As said by @janden above the only other thing that would be great to have is an insurance that this is not a regression in speed, or, actually more strongly an improvement -- it should be due to the generation of fewer filters (and the current absence of filter caching)

**Comment by f0k** [comment]
So to conclude, there shouldn't be any test added to this PR, but in the long run we'd want #259 to ensure that we don't introduce performance regressions (similarly to how you already test for code coverage not being reduced). Correct? Then this would be good to merge.

**Pull request merged**
