### PR TITLE
DOC updated contributing guidelines

### PR DESCRIPTION
**Pull request by cyrusvahidi**
`CONTRIBUTING.MD` has been updated with guidelines on making feature requests and bug fixes

* It explicitly outlines that an issue or feature request should be submitted before a PR
* The community will discuss the feature request and its roadmap
* Features for a PR should be planned to be small and manageable

### CODE REVIEW

**Review by janden — APPROVED** [review]

**Comment by janden** [comment]
Can you also update the e-mail address in the code of conduct?

**Comment by MuawizChaudhary** [comment]
> Can you also update the e-mail address in the code of conduct?

This pr should be committed to main perhaps. 

soliciting community thoughts would also be a good idea on the code of conduct.

**Comment by rastegah** [comment]
done

**Review by janden — APPROVED** [review]
Thanks!

**Pull request merged**
