### PR TITLE
API Change coefficient order

### PR DESCRIPTION
**Pull request by janden**
See title.

### CODE REVIEW

**Comment by janden** [comment]
This will break the build. Fixing the test right now.

**Comment by lostanlen** [comment]
Would be good if this PR could point to an open issue that it would thereby close. So that the issue can have a milestone

**Comment by janden** [comment]
Partially fixes #248.

**Comment by janden** [comment]
> This LGTM, but maybe another 1D person should take a look at this.

That would be @lostanlen. Can you look through this and merge if it looks good?

> Can you squash the TST commit into the API commit before merging?

Done.

**Comment by lostanlen** [comment]
LGTM

**Comment by janden** [comment]
Thank you!

**Pull request merged**
