### PR TITLE
Bug fixed: orders_1_and_2

### LINKED ISSUE #303: BUG scattering3d_qm7.py
It seems that line 180 should be modified as follows:
Current:
order_0, order_1, order_2 = [], [], []
Should be:
order_0, orders_1_and_2 = [], []

### PR DESCRIPTION
**Pull request by nshervt**
[EDIT by @lostanlen: closes #303 ]

### CODE REVIEW

**Comment by eickenberg** [comment]
Cool, thanks! Does the example run through completely with this change?

**Comment by janden** [comment]
Running it. There was another bug (see #308) preventing it from running, but it seems to be on its merry way now. Will merge as soon as it finishes.

**Comment by janden** [comment]
Seems to work. I get the output:
```
Ridge regression, alpha: 0.1, MAE: 4.911195755004883, RMSE: 6.90034818649292
Ridge regression, alpha: 0.01, MAE: 4.034888744354248, RMSE: 5.778854846954346
Ridge regression, alpha: 0.001, MAE: 3.3446338176727295, RMSE: 4.842739105224609
Ridge regression, alpha: 0.0001, MAE: 2.9704883098602295, RMSE: 4.403475284576416
Ridge regression, alpha: 1e-05, MAE: 2.801150321960449, RMSE: 4.204596996307373
Ridge regression, alpha: 1e-06, MAE: 2.742659568786621, RMSE: 4.122145175933838
Ridge regression, alpha: 1e-07, MAE: 2.751904249191284, RMSE: 4.104255199432373
Ridge regression, alpha: 1e-08, MAE: 2.9777421951293945, RMSE: 4.275634288787842
Ridge regression, alpha: 1e-09, MAE: 3.2388601303100586, RMSE: 4.525323390960693
```
Merging.

**Comment by eickenberg** [comment]
merci joakim! that looks like a good result!

**Comment by eickenberg** [comment]
@janden did you need to push something to this PR or can it be merged?

**Comment by janden** [comment]
@eickenberg Yeah I'll squash and add to the contributors file.

**Pull request closed without merging**
