### PR TITLE
Remove vectorize + write frontend-agnostic runtime checks

### LINKED ISSUE #843: `vectorize` should be removed
In Scattering1D
`vectorize=True` should become `out_type="array"`
`vectorize=False` should become `out_type="list"`

It's already being deprecated for a while now, so this removal can be included for v0.3

### PR DESCRIPTION
**Pull request by lostanlen**
Fix #843 
(a second attempt after some productive discussions during review of #844)

This is a planned change for v0.3

The default behavior is still `out_type="array"` (`vectorize=True`)
We introduce `out_type="dict"` to replicate the behavior of `out_type="array", vectorize=False`

A net reduction in code size thanks to utility methods `_check_runtime_args()` and `_check_input()` in `ScatteringBase1D`

Written on top of #860. I suggest we look at #860 first
Tests pass locally

Note that vectorize is still documented in the base frontend. I'll take care of updating these docs after code review.

### CODE REVIEW

**Review by MuawizChaudhary — APPROVED** [review]
Pro merging once the Jenkins finishes building

**Comment by MuawizChaudhary** [comment]
hmmmm seems like the Jenkins aborted

**Comment by lostanlen** [comment]
but Jenkins passed on #862, which contains this PR ?!

**Comment by MuawizChaudhary** [comment]
Tests pass on my end, dunno whats up with Jenkins here.

**Pull request merged**
