### PR TITLE
REF Rename entry point classes and move them into separate modules

### PR DESCRIPTION
**Pull request by janden**

### CODE REVIEW

**Comment by janden** [comment]
> Greek job!

Hehe...

**Comment by edouardoyallon** [comment]
rebase and merge?

**Comment by janden** [comment]
> rebase and merge?

Yes. On it.

**Comment by edouardoyallon** [comment]
> > rebase and merge?
> 
> Yes. On it.

<o/

**Comment by janden** [comment]
# [Codecov](https://codecov.io/gh/kymatio/kymatio/pull/556?src=pr&el=h1) Report
> Merging [#556](https://codecov.io/gh/kymatio/kymatio/pull/556?src=pr&el=desc) into [0.2.X](https://codecov.io/gh/kymatio/kymatio/commit/454306ca14e6401411cf67cf1e85a099e007bbf2&el=desc) will **increase** coverage by `0.00%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/kymatio/kymatio/pull/556?src=pr&el=tree)

```diff
@@           Coverage Diff           @@
##            0.2.X     #556   +/-   ##
=======================================
  Coverage   92.40%   92.41%           
=======================================
  Files          72       72           
  Lines        4070     4072    +2     
=======================================
+ Hits         3761     3763    +2     
  Misses        309      309           
```

| Flag | Coverage Δ | |
|---|---|---|
| #jenkins_main | `92.36% <100.00%> (+<0.01%)` | :arrow_up: |
| #travis | `83.93% <100.00%> (+<0.01%)` | :arrow_up: |

| [Impacted Files](https://codecov.io/gh/kymatio/kymatio/pull/556?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [kymatio/scattering2d/frontend/entry.py](https://codecov.io/gh/kymatio/kymatio/pull/556/diff?src=pr&el=tree#diff-a3ltYXRpby9zY2F0dGVyaW5nMmQvZnJvbnRlbmQvZW50cnkucHk=) | `100.00% <0.00%> (ø)` | |
| [kymatio/scattering1d/frontend/entry.py](https://codecov.io/gh/kymatio/kymatio/pull/556/diff?src=pr&el=tree#diff-a3ltYXRpby9zY2F0dGVyaW5nMWQvZnJvbnRlbmQvZW50cnkucHk=) | `100.00% <0.00%> (ø)` | |
| [kymatio/frontend/entry.py](https://codecov.io/gh/kymatio/kymatio/pull/556/diff?src=pr&el=tree#diff-a3ltYXRpby9mcm9udGVuZC9lbnRyeS5weQ==) | `100.00% <0.00%> (ø)` | |
| [kymatio/scattering3d/frontend/entry.py](https://codecov.io/gh/kymatio/kymatio/pull/556/diff?src=pr&el=tree#diff-a3ltYXRpby9zY2F0dGVyaW5nM2QvZnJvbnRlbmQvZW50cnkucHk=) | `100.00% <0.00%> (ø)` | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/kymatio/kymatio/pull/556?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/kymatio/kymatio/pull/556?src=pr&el=footer). Last update [454306c...8970a03](https://codecov.io/gh/kymatio/kymatio/pull/556?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Pull request merged**
