### PR TITLE
set version to 0.3.dev0 in dev branch

### PR DESCRIPTION
**Pull request by lostanlen**
PEP440 compliant
follows sklearn convention https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/__init__.py#L26

### CODE REVIEW

**Comment by edouardoyallon** [comment]
hmmmmmmmmmmmmm can i ask how this will affect pypi

**Comment by lostanlen** [comment]
@edouardoyallon the idea is to never release `dev` on PyPI but rather to make `master`-based releases
Hence there will never be a `*.dev0` version on PyPI

**Comment by lostanlen** [comment]
@edouardoyallon see:
```
# https://www.python.org/dev/peps/pep-0440/
#
# Generic release markers:
#   X.Y.0   # For first release after an increment in Y
#   X.Y.Z   # For bugfix releases
#
# Admissible pre-release markers:
#   X.Y.ZaN   # Alpha release
#   X.Y.ZbN   # Beta release
#   X.Y.ZrcN  # Release Candidate
#   X.Y.Z     # Final release
#
# Dev branch marker is: 'X.Y.dev' or 'X.Y.devN' where N is an integer.
# 'X.Y.dev0' is the canonical version of 'X.Y.dev'
#
```

**Review by janden — CHANGES_REQUESTED** [review]
Why is the short version `0.3s`? I'm not seeing any of this in the references you provide.

**Comment by lostanlen** [comment]
oops! sorry, that's my mistake. the `s` is a typo. Good catch @janden
Fixed in 2758520

**Comment by janden** [comment]
Ah that explains it… All good then!

**Review by janden — APPROVED** [review]

**Pull request merged**
