### PR TITLE
API Change coeff order

### PR DESCRIPTION
**Pull request by eickenberg**
Done the change. The current state of the PR should fail on travis because tests don't reflect change

### CODE REVIEW

**Comment by lostanlen** [comment]
This is an API-breaking change. Does it make it to `0.1`? If not, it needs to be postponed to the next deprecation cycle ...

**Comment by eickenberg** [comment]
With the modified test it should now pass

**Comment by eickenberg** [comment]
> This is an API-breaking change. Does it make it to 0.1? If not, it needs to be postponed to the next deprecation cycle ...

Then we mess up anybody who is not doing deep learning. And even them if they reuse a saved model

**Comment by lostanlen** [comment]
@eickenberg yes, i would be in favor of including this to 0.1.0-alpha

**Pull request merged**
