### PR TITLE
Simplify scattering1d/filter_bank (bis)

### LINKED ISSUE #513: scattering1d/filter_bank module has too many functions
13 functions, most of them only called once or twice. Surely we can simplify that.

### PR DESCRIPTION
**Pull request by janden**
closes #513 (eventually)
variant of #514, except it's from a branch on lostanlen/kymatio as opposed to kymatio/kymatio

### CODE REVIEW

**Comment by MuawizChaudhary** [comment]
I'll look to push this forward in the next fewdays (maybe tonight)

**Comment by janden** [comment]
There's some problems with the commit history here (looks like it branched off of and old master). I've rebased this locally but can't push without @lostanlen giving permission. Can you enable edits from maintainers?

Also, what's the status on this branch? Is it more or less ready for merging?

**Comment by eickenberg** [comment]
This still needs rebasing, am I correct?

**Comment by janden** [comment]
Ping @lostanlen.

**Comment by janden** [comment]
@lostanlen Would be good to close this out before the sprint. Was there anything else to do here?

**Comment by lostanlen** [comment]
it's ready! happy to see it merged finally

**Comment by janden** [comment]
Good. I've rebased this onto the current dev so the tests should run. Could you clean up the commit history? I'll get started on reviewing it soon.

**Comment by lostanlen** [comment]
clean up the commit history? should i git squash?

**Comment by lostanlen** [comment]
@janden what do you recommend we do with this PR?

**Comment by janden** [comment]
> clean up the commit history? should i git squash?

What I meant is the following:
- Squash any small typo or bugfix commits (like “bis” and “remove spaces around ** operator” etc.).
- Make sure that each commit passes the test suite.
- Fix the messages so they follow the style (ENH, FIX, etc.).

**Comment by edouardoyallon** [comment]
@lostanlen I'd like to help you with this, ping me when you have a chance to get some spare time.

**Comment by OverLordGoldDragon** [comment]
Seems it's this, Stride, and JFTS before v0.3.0 ... or is it [all this](https://github.com/kymatio/kymatio/milestone/6)?

**Comment by eickenberg** [comment]
Certainly not all that.
A couple things more though that we had discussed.
E.g. I'm adding the JAX backend in for 0.3

**Comment by lostanlen** [comment]
i'll let @eickenberg @edouardoyallon be the judge for the v0.3 final cut
my impression is that JTFS is best left to v0.4

**Comment by OverLordGoldDragon** [comment]
With uncertainty on how long v0.4.0 will take, I'd rather see it merged earlier. JFTS seems a small enough addon; if need be, can make it smaller for v0.3.0 then resume dev for 0.4.0, but think we'll manage.

**Comment by MuawizChaudhary** [comment]
Closed as superseded by #833

**Pull request closed without merging**
