### PR TITLE
ENH removing the unused library warnings and importing the correct one in 3D

### LINKED ISSUE #177: [BUG] unimported warnings in cdgmm3d
The warnings for non-contiguous inputs in the PyTorch backend of `cdgmm3d` need to be prefaced by an `import warnings` statement

https://github.com/kymatio/kymatio/blob/master/kymatio/scattering3d/backend/backend_torch.py#L69

https://github.com/kymatio/kymatio/blob/master/kymatio/scattering3d/backend/backend_torch.py#L72

Besides, the error messages should not end with exclamation marks. They add insult to injury.

tagging @louity

### PR DESCRIPTION
**Pull request by edouardoyallon**
Close #177

### CODE REVIEW

**Comment by lostanlen** [comment]
Thanks. I think that scattering3d has the opposite problems: it uses `warnings` without importing them. See #177
Could you do this in this PR too?

**Comment by edouardoyallon** [comment]
@lostanlen This fixes your issue + two unused library dependancy removed in this file.

**Comment by lostanlen** [comment]
Perfect, thanks! :) Once this passes I'll be down for a rebase&merge

**Comment by edouardoyallon** [comment]
> Perfect, thanks! :) Once this passes I'll be down for a rebase&merge

Why not Squash and merge?

**Pull request merged**
