### PR TITLE
ENH 1d zero padding and complex FFT

### PR DESCRIPTION
**Pull request by lostanlen**
for JTFS (the frequential scattering part, specifically)

tests included

### CODE REVIEW

**Review by cyrusvahidi — COMMENTED** [review]
for frequential scattering we're going to zero pad the upper part of frequency axis?

**Review by cyrusvahidi — APPROVED** [review]
introduces `cfft` primitive and allows for pad modes in the padding primitive. tested neatly.

**Comment by lostanlen** [comment]
>  for frequential scattering we're going to zero pad the upper part of frequency axis?

the lower part. "right" is down in wavelet space ;)

**Comment by cyrusvahidi** [comment]
> > for frequential scattering we're going to zero pad the upper part of frequency axis?
> 
> the lower part. "right" is down in wavelet space ;)

as j -> 0 :-D

**Pull request merged**
