### PR TITLE
DOC Fix sphinx changelog

### PR DESCRIPTION
**Pull request by janden**
Extracted the relevant bits from the sklearn sphinx setup. Also did some minor reformatting. Result looks like this:
image

### CODE REVIEW

**Comment by lostanlen** [comment]
Too bad that we have _italics_  and `constant_width` co-existing in the changelog :/

**Comment by janden** [comment]
> Too bad that we have _italics_ and `constant_width` co-existing in the changelog :/

Missed those ones. Fixed now.

**Comment by janden** [comment]
Any chance someone has time to look at this? Once this is done we can push v0.3.0 out.

**Comment by janden** [comment]
Ping @lostanlen @eickenberg.

**Review by lostanlen — APPROVED** [review]
many thanks

**Pull request merged**
