### PR TITLE
FFT SciPy

### PR DESCRIPTION
**Pull request by MuawizChaudhary**
This pull request replaces the use of the NumPy FFT with the SciPy FFT.

### CODE REVIEW

**Comment by edouardoyallon** [comment]
Please rebase!

**Comment by lostanlen** [comment]
LGTM. I appreciate that you included `axis` as a kwarg. This will be useful down the line for implementing time-frequency scattering.

**Comment by edouardoyallon** [comment]
I'd like @janden to have a look

**Comment by lostanlen** [comment]
would be nice to benchmark this too!

**Pull request merged**
