### PR TITLE
[WIP] ENH JTFS PyTorch frontend

### PR DESCRIPTION
**Pull request by lostanlen**

### CODE REVIEW

**Comment by lostanlen** [comment]
will make a separate PR for this `pad_frequency` primitive

**Review by cyrusvahidi — COMMENTED** [review]
I will add some differentiability tests beyond `U_0`

**Comment by lostanlen** [comment]
@cyrusvahidi thanks. yes, please add some `assert`'s for differentiability.

**Comment by lostanlen** [comment]
conflict's maximally resolved

**Comment by lostanlen** [comment]
@cyrusvahidi LMK when this is ready for review + merge

**Comment by lostanlen** [comment]
sweetest

**Pull request merged**
